### DISCUSSION TITLE
Modifying html-slider-response

### DISCUSSION THREAD

**Discussion by j22tis** [jspsych/jsPsych#1660] [Q&A] [answered]
Hi! 

I'm looking for some advice on how would I go about modifying slider-response plugin, so that:

1. The slider thumb would not appear at the beginning of the trial, but only when clicked on the slider. (I tried changing the css file thumb parameters, but this seems to have no effect).

2. The slider response would be collected and the trial ends with just a click on the slider, without additional confirmation. 

Cheers,
Alan

**Comment by becky-gilbert** [comment, marked as answer]
Hi @j22tis! To hide the slider thumb, you can remove the CSS rules that set the custom thumb appearance in the jspsych.css file, i.e. the commented-out stuff below. The only bit you want to keep is the `-webkit-appearance: none;` for `.jspsych-slider::-webkit-slider-thumb`:
```css
/* thumb */
.jspsych-slider::-webkit-slider-thumb {
  /* border: 1px solid #666;
  height: 24px;
  width: 15px;
  border-radius: 5px;
  background: #ffffff;
  cursor: pointer;
  margin-top: -9px; */
  -webkit-appearance: none;
}
/* .jspsych-slider::-moz-range-thumb {
  border: 1px solid #666;
  height: 24px;
  width: 15px;
  border-radius: 5px;
  background: #ffffff;
  cursor: pointer; 
}
.jspsych-slider::-ms-thumb {
  border: 1px solid #666;
  height: 20px;
  width: 15px;
  border-radius: 5px;
  background: #ffffff;
  cursor: pointer;
  margin-top: -2px; 
} */
```
I think you also need to set the `visibility` to `hidden` for the `-ms-thumb` and `-moz-range-thumb` pseudo-classes. You could either add this to jspsych.css or put it in `style` tags in your HTML file.
```css
.jspsych-slider::-ms-thumb {visibility: hidden;}
.jspsych-slider::-moz-range-thumb {visibility:hidden;}
```

To get the trial to end when the slider is clicked, you can find the line in the plugin that sets up the click event listener for the next button ([line 153](https://github.com/jspsych/jsPsych/blob/bf9dec250b7fcd038171cb3a1aad5647d5bb67e7/plugins/jspsych-html-slider-response.js#L153) in html-slider-response in jsPsych v6.3.0):
```js
display_element.querySelector('#jspsych-html-slider-response-next').addEventListener('click', function() { ... }
```
And change this so that the click handler function is applied to the slider instead of the next button. The slider ID is "jspsych-html-slider-response-response", so you would change that line to this:
```js
display_element.querySelector('#jspsych-html-slider-response-response').addEventListener('click', function() { ... }
```
Then as long as the trial's `response_ends_trial` parameter is `true`, the trial should end immediately after the slider is clicked.

The trickier part is getting the thumb to reappear when the slider has been clicked. This is tricky because you can't use JavaScript to set CSS rules for _pseudo-classes_ in the same way that you can for other CSS selectors. But if I understand correctly, it sounds like you want the trial to end anyway when the person clicks the slider, so maybe showing the thumb isn't that important? If it is, you can have a look at the responses to this [stackoverflow post](https://stackoverflow.com/questions/311052/setting-css-pseudo-class-rules-from-javascript) about setting CSS pseudo-class rules with JavaScript, and then add the code for this inside the slider's click event handler.

I hope this helps!
