### DISCUSSION TITLE
Slider with out blue bar

### DISCUSSION THREAD

**Discussion by valentinavellani** [jspsych/jsPsych#2558] [Q&A]
Hi,
 I am using an old version of jsPsych in which the slider plug in has a blue bar.
I have everything set to be on this version, so I was wondering whether there is a way to make the bar transparent without converting the whole task to a new version of JsPsych.

Thank you very much
Valentina

**Comment by jodeleeuw** [comment]
Hi @valentinavellani,

You can probably use the CSS from the newer version of jsPsych, though I am not certain about this. Here's the relevant chunk that styles the slider elements:

```css
/* custom style for input[type="range] (slider) to improve alignment between positions and labels */

.jspsych-slider {
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  width: 100%;
  background: transparent;
}
.jspsych-slider:focus {
  outline: none;
}
/* track */
.jspsych-slider::-webkit-slider-runnable-track {
  appearance: none;
  -webkit-appearance: none;
  width: 100%;
  height: 8px;
  cursor: pointer;
  background: #eee;
  box-shadow: 0px 0px 0px #000000, 0px 0px 0px #0d0d0d;
  border-radius: 2px;
  border: 1px solid #aaa;
}
.jspsych-slider::-moz-range-track {
  appearance: none;
  width: 100%;
  height: 8px;
  cursor: pointer;
  background: #eee;
  box-shadow: 0px 0px 0px #000000, 0px 0px 0px #0d0d0d;
  border-radius: 2px;
  border: 1px solid #aaa;
}
.jspsych-slider::-ms-track {
  appearance: none;
  width: 99%;
  height: 14px;
  cursor: pointer;
  background: #eee;
  box-shadow: 0px 0px 0px #000000, 0px 0px 0px #0d0d0d;
  border-radius: 2px;
  border: 1px solid #aaa;
}
/* thumb */
.jspsych-slider::-webkit-slider-thumb {
  border: 1px solid #666;
  height: 24px;
  width: 15px;
  border-radius: 5px;
  background: #ffffff;
  cursor: pointer;
  -webkit-appearance: none;
  margin-top: -9px;
}
.jspsych-slider::-moz-range-thumb {
  border: 1px solid #666;
  height: 24px;
  width: 15px;
  border-radius: 5px;
  background: #ffffff;
  cursor: pointer;
}
.jspsych-slider::-ms-thumb {
  border: 1px solid #666;
  height: 20px;
  width: 15px;
  border-radius: 5px;
  background: #ffffff;
  cursor: pointer;
  margin-top: -2px;
}
```
