### DISCUSSION TITLE
Vertical oriented slider

### DISCUSSION THREAD

**Discussion by steffejr** [jspsych/jsPsych#3441] [General]
Hello,
I would like to make a visual analog scale with a vertical orientation. Is this possible?
Thank you

**Comment by ChristopheBossens** [comment]
Yes, but it might affect how your overall trial looks. Can you add the following code to the head section of your page and see what the effect is? It uses css transformations to rotate the scale

```css
input[type="range"] {
   position: absolute;
   top: 40%;
   transform: rotate(270deg);
}
```
