### ISSUE TITLE
Google fonts loaded from third party server - GDPR

### ISSUE THREAD

**Issue by adriansteffan** [jspsych/jsPsych#2153]
In `jspsych.css`, the Google font "Open Sans" is loaded via googleapis.com. Under European data protection laws, this request needs the explicit opt-in permission of the website visitor. However, most psych labs don't know about that and open themselves up to GDPR complaints by using jspsych for their experiments. It might be better to include Open Sans locally or switch to Arial for the time being.

**Comment by adriansteffan** [comment]
Sorry to bother again, but there has now been a precedent case in Germany that ruled this exact usage of Google fonts illegal and fineable https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/

Therefore, any lab in the EU that is not explicitly removing the Google fonts cdn request from their jspsych installation is breaking the law.

**Comment by jodeleeuw** [comment]
@bjoluc I'm trying to search for details about how SASS would inline the font, but not finding quick answers. Won't we have to host the font file somewhere?

**Comment by bjoluc** [comment]
@jodeleeuw The post I read was misleading: Turns out, Sass itself doesn't offer to inline fonts. So I went for webpack and some plugins to do the job. The result looks like this (many times, for all variations):
```css
/* open-sans-cyrillic-ext-400-italic*/
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-display: swap;
  font-weight: 400;
  src: url(data:font/woff2;charset=utf-8;base64,d09GMgABAA[...]) format('woff2'), url(data:font/woff;charset=utf-8;base64,d09GRgABAA[...]) format('woff');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
```
Sadly, without further ado, the css file becomes 3.3Mb large. We could certainly half that by excluding the nowadays legacy `woff` format and only keeping `woff2` (just as https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700 does). But that's still pretty large for a first-load css file :confused:

> Won't we have to host the font file somewhere?

I think that would only shift the problem since jsPsych experiments would still use external servers. Oh wait, I looked at the verdict again: One particular reason for the fine was that the 3rd party is Google, which is known to collect and process user data.

@adriansteffan WDYT: Suppose we switch to a service that is guaranteed to not keep logs, would that fix the problem, or just make it less heavy?
