### ISSUE TITLE
Youtube-style full-screen video

### ISSUE THREAD

**Issue by derekalbert** [jspsych/jsPsych#3216]
Hi, I'm wondering if it's possible to have a video scale right to the edge of the screen when in full-screen mode? I set my video height and width to 100%, but there's still white-space around it. I'm assuming that it has to do with the CSS styling. Can you suggest how to achieve YouTube-style full-screen video playback by adjusting the styling, perhaps with css_classes, or by some other means? Thanks!

EDIT: Just to clarify, I'm using the video-keyboard-response plugin, and here is my code:

    var video = {
        type: jsPsychVideoKeyboardResponse,
        stimulus: [videoSource],
        start: jsPsych.timelineVariable('start'),
        stop: jsPsych.timelineVariable('stop'),
        trial_ends_after_video: true,
        height: '100%',
        width: '100%',
        response_ends_trial: false,
        choices: [' '],
        data: {
            stim_type: 'video',
            start: jsPsych.timelineVariable('start'),
            stop: jsPsych.timelineVariable('stop')
        },
    }

**Comment by Shaobin-Jiang** [comment]
Example javascript code (I have only added `css_classes` here):

```javascript
const jspsych = initJsPsych();

jspsych.run([{
    type: jsPsychVideoKeyboardResponse,
    stimulus: ['./video.mp4'],
    width: '100%',
    height: '100%',
    css_classes: ['fullscreen-video'],
}]);
```

Corresponding CSS code:

```css
.fullscreen-video {
    max-width: 100vw;
}

.fullscreen-video>div {
    height: 100vh;
    width: 100vw;
}

.fullscreen-video video {
    object-fit: fill;
    position: fixed;
    left: 0;
    top: 0;
}
```
