### ISSUE TITLE
Content does not automatically center in IE11

### ISSUE THREAD

**Issue by dschreij** [jspsych/jsPsych#587]
I know, why do people still use it, but some insist on maintaining backward compatibility with IE. By default, jsPsych didn't center the content for me, so I had to add these styles:

```css
  .jspsych-content-wrapper {
    min-height: 100vh;
    min-width: 100vw;
    display: -ms-flexbox;
    -ms-flex-direction: column;
  }

  #jspsych-content {
    -ms-flex-grow: 1
  }
```
maybe add these by default? They do not appear to be disruptive for other browsers.
