### ISSUE TITLE
Investigate button highlight persisting on mobile devices

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#977]
See #966 for context.

**Comment by jodeleeuw** [comment]
I created a demo on cognition.run to test this on mobile:

https://3lwtdgydzs.cognition.run/

**Comment by becky-gilbert** [comment]
Josh, your example task worked fine on my mobile phone (Android Chrome), but I was able to reproduce the problem on an iPad (iOS 9 Safari). On the iPad, the last button that was pressed stays highlighted when the next button-response trial loads. I'll look into this to see if there's a fix that could be implemented in the plugin.

**Comment by becky-gilbert** [comment]
I think the reason for this is that a touch event in iPad Safari (and maybe other touch devices/browsers?) causes the button to change to the CSS 'hover' state, and for some reason that button stays in the hover state after it's been touched. So the button:hover CSS doesn't go away until another button is pressed. This is explained on this stackoverflow question: https://stackoverflow.com/questions/10642953/mobile-safari-links-retains-focus-after-touch

Since the hover state doesn't make sense for touch-only devices, one fix for this is to use a CSS media query so that the .jspsych-btn:hover style is only applied to devices that have a pointing device that can hover, e.g. a mouse. Here's some CSS that can be added after the jspsych.css stylesheet:
```css
/* overwrite the button hover style properties that are set in jspsych.css */
.jspsych-btn:hover {
    background-color: #fff;
    border-color: #ccc;
}
/* only apply the hover style when there's a pointing device that can hover */
@media (hover: hover) {
    .jspsych-btn:hover {
        background-color: #ddd;
        border-color: #aaa;
    }
}
```
I created a demo here using this CSS: https://sb1czt0wmx.cognition.run
It seems to me like it works, i.e. the buttons show the hover style on devices with a mouse, but the button highlighting doesn't happen on iPads. And I haven't had a chance to test on devices that have both touchscreen capabilities and a mouse.

The downside of this solution is that I don't know how to add a visual indicator that the button has been pressed on iPads (setting style for the button's active state didn't work).

**Comment by becky-gilbert** [comment]
Update: 

I was wrong about the active state CSS not working. Here's the updated CSS used in my cognition.run demo here: https://sb1czt0wmx.cognition.run
```css
/* this is just included to overwrite the button's hover style properties that are set in jspsych.css */
.jspsych-btn:hover {
    background-color: #fff;
    border-color: #ccc; 
}

.jspsych-btn:active {
    background-color: #ddd;
    border-color: #000000;
}

/* only apply the hover style when there's a pointing device that can hover */
@media (hover: hover) {
    .jspsych-btn:hover {
        background-color: #ddd;
        border-color: #aaa;
    }
}
```
I also did more testing and found that while this fixes the problem on iPads, the problem still exists on touchscreen-enabled laptops. The problem is that there's no way to use CSS media queries to apply different styles on devices that have _both_ touchscreen and a pointer/mouse (see [here](https://css-tricks.com/touch-devices-not-judged-size/) and [here](https://drafts.csswg.org/mediaqueries/#any-input)). On touchscreen-enabled laptops, things work fine with the mouse, but the persistent highlighting problem occurs when the button response is made with a touch rather than mouse click. I think there's no pure CSS way to handle this. The only solutions I can think of are to (1) add a touch event listener to all button-response plugins that removes the hover style or the button's focus after a touch event, or (2) get rid of the :hover styles.

So to summarize what I've found using the CSS above:
 
**iPad (iOS 10) Safari**
Putting the hover styles in a media query fixes the persistent highlighting problem, and the addition of :active styles gives a visual indicator that the button has been pressed.

**Laptop with both mouse and touchscreen**
Both the hover and active states work fine when using the mouse, but the persistent hover-related highlighting problem occurs with a touch response.

**Non-touchscreen desktop/laptop, Chrome**
Both active and hover states work fine.

**Non-touchscreen desktop/laptop, Firefox and Edge**
Hover state works fine, but the :active styles aren't applied when the button is clicked. Apparently [the active state is blocked in these browsers by the preventDefault() function](https://www.nickhart.co.uk/2019/03/12/unusual-behaviour-in-firefox-when-using-preventdefault/) that's called in the button's click event listener.

@jodeleeuw are you ok with these CSS changes?
